#!/usr/bin/env node
// Reported revenue job: net revenue by brand, as the companies tag it in the XBRL of their periodic SEC filings.
//   node jobs/fetch-revenue.mjs             companies checked in the last 20 hours are skipped
//   node jobs/fetch-revenue.mjs --force     check every company again
//   MIP_REVENUE_TA=IDERM                     only the companies of one therapeutic area (testing)
// Writes data/revenue.js (window.MIP_REVENUE), which the app loads when a panel needs it.
//
// How it works (SEC EDGAR only; no key, but the SEC requires a declared contact, so the job needs MIP_CONTACT_EMAIL):
//   1. The companies of the catalog's US brands (js/catalog.js, every area) are matched by name to SEC registrants
//      (company_tickers.json). Companies that do not file with the SEC (private, or listed only outside the US) are listed
//      as not matched.
//   2. For each registrant, the latest annual report (10-K, or 20-F / 40-F) and the quarterly reports (10-Q) around it
//      are read from its inline XBRL instance: the latest 10-K, the 10-Qs filed after it and the one before it, which
//      together hold eight consecutive quarters and three fiscal years.
//   3. Revenue facts (us-gaap Revenues and RevenueFromContractWithCustomer..., ifrs-full Revenue...) broken down by product
//      (ProductOrServiceAxis; ProductsAndServicesAxis under IFRS) are kept when the product member's name matches a catalog
//      brand (ZORYVE for arqt:ZORYVECream0.3Member; members of one brand are added up unless one is the brand itself). A
//      grouping axis next to the product (portfolio, business segment) is allowed; a split by region, customer or
//      collaboration arrangement is not, so a brand the filer reports only by region is not found.
//   4. Quarters are the 3-month facts; a missing fourth quarter is the fiscal year less the nine months, and a missing
//      second or third quarter the half-year or nine months less the earlier ones. A brand reported by several filers
//      (co-marketed) keeps the filer with the most revenue; the others are listed.
// Each filing is read once (the ledger in data/revenue.js) and its instance is not cached on disk. MIP_REVENUE_MAX_FILINGS
// (default 60) and MIP_REVENUE_MAX_MIN (default 12) cap a run; the rest is read on the next runs.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { upstream, CONTACT } from './upstream.mjs';

const require = createRequire(import.meta.url);
const CAT = require('../js/catalog.js');
const { match } = require('../js/sources.js');

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', 'data', 'revenue.js');
const args = process.argv.slice(2);
const FORCE = args.includes('--force');
const num = (v, d) => (Number(v) > 0 ? Number(v) : d);
const MAX_FILINGS = num(process.env.MIP_REVENUE_MAX_FILINGS, 60), MAX_MIN = num(process.env.MIP_REVENUE_MAX_MIN, 12);
const ONLY_TA = process.env.MIP_REVENUE_TA || '';
const now = new Date(), t0 = Date.now(), deadline = t0 + MAX_MIN * 60000;
const DAY = 864e5, RECHECK_MS = 20 * 3600000;
const log = (...a) => console.log(...a);
const uniq = (a) => Array.from(new Set(a));

function readPrev() {
  try { const ctx = { window: {} }; vm.runInNewContext(fs.readFileSync(OUT, 'utf8'), ctx); if (ctx.window.MIP_REVENUE) return ctx.window.MIP_REVENUE; } catch { /* first run */ }
  return {};
}
const prev = readPrev();
function write(payload) {
  const header = `/* Net revenue by brand from the XBRL of periodic SEC filings (10-K, 10-Q, 20-F), generated by jobs/fetch-revenue.mjs on ${payload.generated_utc}.\n   Source: SEC EDGAR. Do not edit by hand: rerun the script. */\n`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT + '.tmp', header + 'window.MIP_REVENUE = ' + JSON.stringify(payload) + ';\n');
  fs.renameSync(OUT + '.tmp', OUT);
}
if (!CONTACT) {
  log('MIP_CONTACT_EMAIL is not set: the SEC refuses requests without a declared contact. Nothing fetched; earlier data kept.');
  write(Object.assign({}, prev, { generated_utc: prev.generated_utc || now.toISOString(), sources: Object.assign({}, prev.sources, { sec: { ok: false, at: now.toISOString(), error: 'Skipped: MIP_CONTACT_EMAIL is not set' } }) }));
  process.exit(0);
}

async function get(url, opts = {}) {
  const m = match(url); if (!m) throw new Error('No source registered for ' + url);
  const r = await upstream(m.key, m.path, opts);
  if (r.status < 200 || r.status >= 300) throw Object.assign(new Error(`HTTP ${r.status} from ${m.key}`), { status: r.status });
  return r.body;
}

/* ---------- Catalog brands and their companies ---------- */
const bnorm = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
const BRANDS = {}; // normalized brand -> { brand, assets: [ids], companies: [catalog names] }
CAT.TAS.filter((t) => !ONLY_TA || t.id === ONLY_TA).forEach((t) => t.assets.forEach((a) => {
  if (!a.brand || bnorm(a.brand).length < 4) return;
  const k = bnorm(a.brand); const b = BRANDS[k] || (BRANDS[k] = { brand: a.brand.toUpperCase(), assets: [], companies: [] });
  if (!b.assets.includes(a.id)) b.assets.push(a.id); if (a.company && !b.companies.includes(a.company)) b.companies.push(a.company);
}));
const BKEYS = Object.keys(BRANDS).sort((x, y) => y.length - x.length);
/* Company names as the SEC lists them, reduced to the distinctive words ("Merck & Co., Inc." and "Merck & Co. (MSD)" both
   become "merck"). A catalog entry "A / B (C)" names three companies; the parent comes first. */
const SUFFIX = /\s+(inc|incorporated|corp|corporation|co|company|plc|ag|sa|nv|se|ltd|limited|llc|lp|holdings?|group|spa|as|ab|kgaa|adr|gmbh|bv|oyj|and|the|pharmaceuticals?|pharma|therapeutics|biotherapeutics|biosciences|biotech|biopharma|biopharmaceuticals|medicines|laboratories|labs)$/;
function cnorm(s) { let x = ' ' + String(s || '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').trim(); let y; do { y = x; x = x.replace(SUFFIX, ''); } while (x !== y); return x.trim(); }
const ALIAS = { bms: 'bristol myers squibb', lilly: 'eli lilly', msd: 'merck', 'j and j': 'johnson and johnson', 'johnson and johnson': 'johnson and johnson', 'merck and co msd': 'merck' };
function namesOf(company) {
  return String(company).split('/').flatMap((p) => { const m = p.match(/^([^(]*)\(([^)]*)\)/); return m ? [m[1], m[2]] : [p]; }).map((x) => x.trim()).filter(Boolean);
}
const COMPANIES = uniq(Object.values(BRANDS).flatMap((b) => b.companies));

/* ---------- XBRL instance: product revenue facts ---------- */
const REV = /^(us-gaap:(RevenueFromContractWithCustomerExcludingAssessedTax|Revenues|RevenueFromContractWithCustomerIncludingAssessedTax|SalesRevenueNet|SalesRevenueGoodsNet)|ifrs-full:(Revenue|RevenueFromContractsWithCustomers|RevenueFromSaleOfGoods))$/;
/* Axes that split a product's revenue into parts (region, customer, collaboration arrangement, consolidation items). */
const SPLIT_AXIS = /Geograph|Region|Country|Market|Customer|Channel|Distribution|Consolidation|Arrangement|Collaborat|Partner|Counterpart|Licens|Range/i;
const REV_RANK = (c) => ['RevenueFromContractWithCustomerExcludingAssessedTax', 'Revenues', 'RevenueFromContractWithCustomerIncludingAssessedTax', 'SalesRevenueNet', 'SalesRevenueGoodsNet', 'Revenue', 'RevenueFromContractsWithCustomers', 'RevenueFromSaleOfGoods'].indexOf(c.split(':')[1]);
function parseInstance(xml) {
  const ctx = {}, units = {};
  for (const m of xml.matchAll(/<(?:xbrli:)?context\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/(?:xbrli:)?context>/g)) {
    const body = m[2]; if (/typedMember/.test(body)) continue;
    const dims = [...body.matchAll(/<(?:xbrldi:)?explicitMember[^>]*dimension="([^"]+)"[^>]*>\s*([^<\s]+)\s*</g)].map((d) => [d[1], d[2]]);
    const s = (body.match(/<(?:xbrli:)?startDate>\s*([^<\s]+)/) || [])[1], e = (body.match(/<(?:xbrli:)?endDate>\s*([^<\s]+)/) || [])[1];
    const prod = dims.filter((d) => /(ProductOrServiceAxis|ProductsAndServicesAxis)$/.test(d[0]));
    if (s && e && prod.length === 1 && !dims.some((d) => SPLIT_AXIS.test(d[0]))) ctx[m[1]] = { s, e, member: prod[0][1].split(':').pop().replace(/Member$/, ''), extra: dims.length - 1 };
  }
  for (const m of xml.matchAll(/<(?:xbrli:)?unit\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/(?:xbrli:)?unit>/g)) { const u = (m[2].match(/iso4217:([A-Z]{3})/) || [])[1]; if (u && !/divide/i.test(m[2])) units[m[1]] = u; }
  const facts = [];
  for (const m of xml.matchAll(/<([\w-]+:\w+)\b([^>]*)>([^<]*)<\/\1>/g)) {
    if (!REV.test(m[1])) continue; const at = m[2]; const c = ctx[(at.match(/\bcontextRef="([^"]+)"/) || [])[1]]; if (!c) continue;
    const u = units[(at.match(/\bunitRef="([^"]+)"/) || [])[1]]; const v = Number(m[3].trim()); if (!u || !isFinite(v)) continue;
    facts.push({ concept: m[1], s: c.s, e: c.e, member: c.member, extra: c.extra, cur: u, v: /\bsign="-"/.test(at) ? -v : v });
  }
  return facts;
}
/* Facts per brand and period: for each product and period the context with the fewest other dimensions (a grouping axis
   such as a portfolio or business segment is allowed; a split by region, customer or arrangement is not) and the first
   concept in REV_RANK; then the brand's own member if the filer tags one, else its members added up. */
function brandFacts(facts) {
  const best = {}; // member|s|e -> chosen fact
  facts.forEach((f) => { const k = f.member + '|' + f.s + '|' + f.e, b = best[k]; if (!b || f.extra < b.extra || (f.extra === b.extra && REV_RANK(f.concept) < REV_RANK(b.concept))) best[k] = f; });
  const byBrand = {};
  Object.values(best).forEach((f) => {
    const mn = bnorm(f.member); const bk = BKEYS.find((k) => mn === k || mn.startsWith(k)); if (!bk) return;
    const per = (byBrand[bk] = byBrand[bk] || {}); const pk = f.s + '|' + f.e; const x = per[pk] || (per[pk] = { exact: null, parts: [], cur: f.cur, concept: f.concept });
    if (mn === bk) x.exact = f; else x.parts.push(f);
  });
  const out = {};
  Object.keys(byBrand).forEach((bk) => Object.keys(byBrand[bk]).forEach((pk) => {
    const x = byBrand[bk][pk]; const list = x.exact ? [x.exact] : x.parts; if (!list.length || list.some((f) => f.cur !== list[0].cur)) return;
    (out[bk] = out[bk] || {})[pk] = { v: list.reduce((s, f) => s + f.v, 0), cur: list[0].cur, members: list.map((f) => f.member), concept: list[0].concept.split(':')[1] };
  }));
  return out;
}
/* Quarters and fiscal years from the facts ('start|end' -> value), deriving missing quarters from the year-to-date facts. */
const days = (s, e) => Math.round((Date.parse(e) - Date.parse(s)) / DAY) + 1;
const kind = (s, e) => { const d = days(s, e); return d >= 84 && d <= 98 ? 'Q' : d >= 175 && d <= 190 ? 'H' : d >= 266 && d <= 280 ? '9M' : d >= 357 && d <= 373 ? 'FY' : null; };
const dayAfter = (e) => new Date(Date.parse(e) + DAY).toISOString().slice(0, 10);
function series(facts) {
  const all = Object.keys(facts).map((k) => { const [s, e] = k.split('|'); return { s, e, v: facts[k][0], k: kind(s, e) }; }).filter((x) => x.k);
  const q = {}; all.filter((x) => x.k === 'Q').forEach((x) => { q[x.e] = { s: x.s, e: x.e, v: x.v }; });
  const find = (k, s, eLo, eHi) => all.find((x) => x.k === k && x.s === s && x.e >= eLo && x.e <= eHi);
  const shift = (e, d) => new Date(Date.parse(e) + d * DAY).toISOString().slice(0, 10);
  all.filter((x) => x.k === 'FY').forEach((fy) => { const n9 = find('9M', fy.s, shift(fy.e, -100), shift(fy.e, -84)); if (n9 && !q[fy.e]) q[fy.e] = { s: dayAfter(n9.e), e: fy.e, v: fy.v - n9.v, derived: 'FY less 9M' }; });
  all.filter((x) => x.k === '9M').forEach((n9) => { const h = find('H', n9.s, shift(n9.e, -100), shift(n9.e, -84)); if (h && !q[n9.e]) q[n9.e] = { s: dayAfter(h.e), e: n9.e, v: n9.v - h.v, derived: '9M less half-year' }; });
  all.filter((x) => x.k === 'H').forEach((h) => { const q1 = find('Q', h.s, shift(h.e, -100), shift(h.e, -84)); if (q1 && !q[h.e]) q[h.e] = { s: dayAfter(q1.e), e: h.e, v: h.v - q1.v, derived: 'half-year less Q1' }; });
  return { q: Object.values(q).sort((a, b) => a.e.localeCompare(b.e)).slice(-12).map((x) => [x.s, x.e, x.v].concat(x.derived ? [x.derived] : [])), fy: all.filter((x) => x.k === 'FY').sort((a, b) => a.e.localeCompare(b.e)).slice(-4).map((x) => [x.s, x.e, x.v]) };
}

/* ---------- Run ---------- */
const payload = {
  generated_utc: now.toISOString(), sources: Object.assign({}, prev.sources || {}),
  companies: Object.assign({}, prev.companies || {}), unmatched: [], facts: Object.assign({}, prev.facts || {}), ledger: Object.assign({}, prev.ledger || {}), brands: {}
};
let read = 0, calls = 0, stopped = '';
try {
  const tick = JSON.parse(await get('https://www.sec.gov/files/company_tickers.json', { maxAgeMs: 7 * DAY })); calls++;
  const REG = {}; Object.values(tick).forEach((r) => { const k = cnorm(r.title); (REG[k] = REG[k] || []).push(r); });
  const cikOf = {}; // catalog company -> [{cik, title, ticker}]
  COMPANIES.forEach((c) => {
    const hits = []; namesOf(c).forEach((n) => { const k = ALIAS[cnorm(n)] || cnorm(n); (REG[k] || []).forEach((r) => { if (!hits.some((h) => h.cik === r.cik_str)) hits.push({ cik: r.cik_str, title: r.title, ticker: r.ticker }); }); });
    if (hits.length) cikOf[c] = hits; else payload.unmatched.push(c);
  });
  const ciks = uniq(Object.values(cikOf).flat().map((h) => h.cik));
  log(`${COMPANIES.length} catalog companies: ${ciks.length} SEC registrants, ${payload.unmatched.length} not matched`);
  for (const cik of ciks) {
    if (Date.now() > deadline) { stopped = 'time cap'; break; }
    const id = String(cik), pad = id.padStart(10, '0'), hit = Object.values(cikOf).flat().find((h) => h.cik === cik);
    const co = payload.companies[id] = Object.assign({ cik: id, name: hit.title, ticker: hit.ticker }, prev.companies && prev.companies[id] ? { filings: prev.companies[id].filings, checked: prev.companies[id].checked, status: prev.companies[id].status } : {});
    co.catalog = Object.keys(cikOf).filter((c) => cikOf[c].some((h) => h.cik === cik));
    if (!FORCE && co.checked && Date.now() - Date.parse(co.checked) < RECHECK_MS) continue;
    let sub; try { sub = JSON.parse(await get('https://data.sec.gov/submissions/CIK' + pad + '.json', { maxAgeMs: 12 * 3600000 })); calls++; } catch (e) { co.status = 'error'; co.error = String(e.message || e).slice(0, 160); continue; }
    co.name = sub.name || co.name;
    const r = sub.filings && sub.filings.recent; const rows = [];
    for (let i = 0; r && i < r.form.length; i++) rows.push({ form: r.form[i], acc: r.accessionNumber[i], filed: r.filingDate[i], period: r.reportDate[i], doc: r.primaryDocument[i], ix: r.isInlineXBRL[i] });
    const periodic = rows.filter((x) => /^(10-K|10-Q|20-F|40-F)$/.test(x.form) && x.ix && /\.htm$/i.test(x.doc)).sort((a, b) => b.filed.localeCompare(a.filed));
    const k = periodic.find((x) => x.form === '10-K');
    let pick = [];
    if (k) { const after = periodic.filter((x) => x.form === '10-Q' && x.filed > k.filed).slice(0, 3); const before = periodic.find((x) => x.form === '10-Q' && x.filed < k.filed); pick = [k].concat(after, before ? [before] : []); }
    else { const f = periodic.find((x) => /^(20-F|40-F)$/.test(x.form)); if (f) pick = [f]; }
    co.checked = new Date().toISOString(); co.form = k ? '10-K' : pick[0] ? pick[0].form : null;
    if (!pick.length) { co.status = 'no periodic XBRL filings'; co.filings = []; continue; }
    co.filings = pick.map((x) => ({ acc: x.acc, form: x.form, filed: x.filed, period: x.period, doc: x.doc })); co.status = 'ok';
    for (const f of pick) {
      const done = payload.ledger[f.acc]; if (done && (ONLY_TA || !done.scope)) continue; // a filing read for one area only is read again in a full run
      if (read >= MAX_FILINGS) { stopped = 'filing cap'; break; }
      if (Date.now() > deadline) { stopped = 'time cap'; break; }
      const url = 'https://www.sec.gov/Archives/edgar/data/' + id + '/' + f.acc.replace(/-/g, '') + '/' + f.doc.replace(/\.htm$/i, '_htm.xml');
      let xml; try { xml = await get(url, { noStore: true, maxAgeMs: 0 }); calls++; read++; } catch (e) { payload.ledger[f.acc] = { cik: id, form: f.form, filed: f.filed, st: e.status === 404 ? 'no instance' : 'error' }; if (e.status !== 404) delete payload.ledger[f.acc]; continue; }
      const bf = brandFacts(parseInstance(xml)); const found = Object.keys(bf);
      const store = (payload.facts[id] = payload.facts[id] || {});
      found.forEach((bk) => { const per = (store[bk] = store[bk] || { cur: null, members: [], p: {} }); Object.keys(bf[bk]).forEach((pk) => { const x = bf[bk][pk]; const old = per.p[pk]; if (!old || old[2] <= f.filed) per.p[pk] = [x.v, f.acc, f.filed]; per.cur = x.cur; per.concept = x.concept; x.members.forEach((m) => { if (!per.members.includes(m)) per.members.push(m); }); }); });
      payload.ledger[f.acc] = { cik: id, form: f.form, filed: f.filed, period: f.period, st: 'ok', brands: found.length }; if (ONLY_TA) payload.ledger[f.acc].scope = ONLY_TA;
      log(`read   ${co.name.slice(0, 32).padEnd(32)} ${f.form.padEnd(5)} ${f.period} ${found.length ? found.map((b) => BRANDS[b].brand).join(', ') : 'no catalog brand tagged'}`);
    }
    if (stopped) break;
  }
  payload.sources.sec = { ok: true, at: new Date().toISOString(), read, calls, stopped: stopped || null };
} catch (e) {
  payload.sources.sec = { ok: false, at: new Date().toISOString(), error: String(e.message || e).slice(0, 200) };
  log('FAILED: ' + payload.sources.sec.error + ' (earlier data kept)');
  payload.unmatched = prev.unmatched || [];
}

/* Brands: each brand's series from every filer that tags it; the filer with the most recent-year revenue first. */
Object.keys(payload.facts).forEach((cik) => Object.keys(payload.facts[cik]).forEach((bk) => {
  const per = payload.facts[cik][bk], b = BRANDS[bk]; if (!b) return;
  const s = series(Object.fromEntries(Object.entries(per.p).map(([k, v]) => [k, v]))); if (!s.q.length && !s.fy.length) return;
  const accs = uniq(Object.values(per.p).map((v) => v[1])).sort().reverse();
  const row = { cik, company: (payload.companies[cik] || {}).name || cik, cur: per.cur, concept: per.concept, members: per.members, q: s.q, fy: s.fy, filings: accs.slice(0, 6) };
  const size = (x) => (x.fy.length ? x.fy[x.fy.length - 1][2] : 0) + (x.q.length ? x.q[x.q.length - 1][2] * 4 : 0);
  const cur = payload.brands[b.brand];
  if (!cur) payload.brands[b.brand] = Object.assign(row, { assets: b.assets, others: [] });
  else if (size(row) > size(cur)) payload.brands[b.brand] = Object.assign(row, { assets: b.assets, others: [{ cik: cur.cik, company: cur.company }].concat(cur.others) });
  else cur.others.push({ cik, company: row.company });
}));
payload.notes = [
  'Net revenue as each filer tags it in the XBRL of its 10-K, 10-Q or 20-F: facts whose only dimension is a product member matching the brand. Global unless the filer reports the brand only by region (then not found).',
  'Quarters are 3-month facts; a missing quarter is derived from the year-to-date facts (marked). Values are in the filer\'s reporting currency (cur).',
  'A co-marketed brand shows the filer reporting the most revenue; partners may report royalties or collaboration revenue instead of sales.'
];
write(payload);
log(`Wrote data/revenue.js · ${Object.keys(payload.brands).length} brands with reported revenue from ${Object.keys(payload.facts).length} filers · ${read} filings read, ${calls} calls${stopped ? ' · stopped at the ' + stopped + '; the rest is read on the next run' : ''} · ${((Date.now() - t0) / 1000).toFixed(0)}s`);
